version: "3.8"

services:
  nuxt:
    build: ./
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3000:3000"
      - "24678:24678"
    volumes:
      - ./:/var/www
    networks:
      - nuxt-network

networks:
  nuxt-network:
    driver: bridge
